#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Number of hellos to generate
gobblin.source.helloWorld.numHellos=100

gobblin.workDir=/tmp/gobblinClusterKillTest

# Job Identification
job.name=HelloWorld
job.group=GobblinSamples
job.description=The "Hello World" Gobblin job

# Source, Converters, Writer, Publisher
source.class=gobblin.util.test.HelloWorldSource
writer.destination.type=HDFS
writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.output.format=txt
#gobblin.writer.throttle_type=QPS
#gobblin.writer.throttle_rate=1

data.publisher.type=gobblin.publisher.BaseDataPublisher
converter.classes=gobblin.converter.string.StringToBytesConverter


data.publisher.final.dir=${gobblin.workDir}/job-output
data.publisher.replace.final.dir=false

# Work paths
state.store.enabled=false
writer.staging.dir=${gobblin.workDir}/writer-staging
writer.output.dir=${gobblin.workDir}/writer-output

# Miscellaneous
job.lock.enabled=false
