apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gaas-ingress
  annotations:
    # utilize an nginx ingress as default, to set up read file at incubator-gobblin/gobblin-docs/user-guide/Azure-Kubernetes-Deployment.md
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  backend:
    serviceName: gaas-svc
    servicePort: 6956
