type=hadoopJava
job.class=org.apache.gobblin.data.management.retention.DatasetCleanerJob

gobblin.retention.dataset.profile.class=org.apache.gobblin.data.management.retention.profile.TrackingDatasetProfile
gobblin.retention.dataset.pattern=${testNameTempPath}/user/gobblin/data/trackingData/*/hourly
gobblin.retention.datetime.pattern=yyyy/MM/dd/HH

# 3 days
gobblin.retention.minutes.retained=4320
gobblin.retention.simulate=false
gobblin.retention.skip.trash=true