language: java

dist: bionic
sudo: required

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libaio-dev
      - libdbus-glib-1-dev
      - xsltproc

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:

services:
  - xvfb
  - mysql

stages:
  - test
  - name: deploy
    if: branch = master

before_script:
  - mysql -uroot -e "create user testUser identified by 'testPassword';"
  - mysql -uroot -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password')"

script:
  - travis_retry ./travis/test.sh
  - travis_retry ./gradlew jacocoTestReport
after_success:
  - bash <(cat .codecov_bash)
after_failure: ./travis/junit-errors-to-stdout.sh

jobs:
  include:
    - stage: deploy
      env: RUN_TEST_GROUP=none
      install: skip
      script:
        - travis_retry ./travis/artifactoryDeploy.sh

env:
  jobs:
    - RUN_TEST_GROUP=build
    - RUN_TEST_GROUP=default
    - RUN_TEST_GROUP=group1
    - RUN_TEST_GROUP=coverage
  global:
    - secure: TihDMhhcX3K1BXV1zCgHYfAa/wxpVOxnMZXbvAoCiA6vbUCd/94bPQaAhABKkZdWUqsgto9YxYyqcQM2XntDXs2K3A8AdW2PUgb9ynf782zFsfG8O2fasW1UQxg4QQ5TQw+P34s7HjUNz0dDfRyl1gurN9yPOPvAxv+paB9FDfE=
    - secure: K/d6ce/NOHkcNfQvFopU5jVkCPwbj8xWTu1vgZiHMOeIB3cU9lZzxQESOZw5zd1aqYDMmTYXU62I/fn0CWTUvfL1TdKFQ4iN0OW31uFr2cFtnCRhxALsRoXYHvApHmssOxuQdp76jAavoHt+CLxcwG/FGZ3GEaczbZC1ZU/pjbQ=
jdk:
  - openjdk8
