language: java

dist: xenial
sudo: required

addons:
  apt:
    packages:
      - libaio-dev
      - libdbus-glib-1-dev
      - xsltproc

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:

services:
  - xvfb
  - mysql

before_script:
  - mysql -uroot -e "create user testUser identified by 'testPassword';"

script:
  - ./travis/test.sh
  - ./gradlew jacocoTestReport

after_success:
  - bash <(cat .codecov_bash)
after_failure: ./travis/junit-errors-to-stdout.sh



env:
  - RUN_TEST_GROUP=build
  - RUN_TEST_GROUP=default
  - RUN_TEST_GROUP=group1
  - RUN_TEST_GROUP=coverage

jdk:
  - openjdk8

matrix:
  exclude:
