language: java

before_install:
  - sudo apt-get sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer

script:
  - ./gradlew clean assemble
  - ./gradlew check 
  - ./gradlew clean check -PuseHadoop2

jdk:
  - oraclejdk8
  - oraclejdk7
