language: java

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libaio-dev
      - libdbus-glib-1-dev
      - xsltproc
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - mysql -uroot -e "create user testUser identified by 'testPassword';"

script: ./travis/test.sh

after_success: ./gradlew coveralls
after_failure: ./travis/junit-errors-to-stdout.sh



env:
  - RUN_TEST_GROUP=build
  - RUN_TEST_GROUP=default
  - RUN_TEST_GROUP=group1
  - RUN_TEST_GROUP=coverage

jdk:
  - oraclejdk8

matrix:
  exclude:
