language: java

addons:
  apt:
    packages:
      - libaio-dev

script:
  - ./gradlew clean check -PskipTestGroup=disabledOnTravis -i
  - ./gradlew clean check -PuseHadoop2 -PskipTestGroup=disabledOnTravis -i

jdk:
  - oraclejdk8
  - oraclejdk7