language: java

dist: bionic
sudo: required

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libaio-dev
      - libdbus-glib-1-dev
      - xsltproc

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:

services:
  - xvfb
  - mysql

stages:
  - test
  - name: deploy
    if: branch = master

before_script:
  - mysql -uroot -e "create user testUser identified by 'testPassword';"
script:
  - travis_retry ./travis/test.sh
  - travis_retry ./gradlew jacocoTestReport
after_success:
  - bash <(cat .codecov_bash)
after_failure: ./travis/junit-errors-to-stdout.sh

jobs:
  include:
    - stage: deploy
      env: RUN_TEST_GROUP=none
      install: skip
      script:
        - ./travis/bintrayDeploy.sh

env:
  jobs:
    - RUN_TEST_GROUP=build
    - RUN_TEST_GROUP=default
    - RUN_TEST_GROUP=group1
    - RUN_TEST_GROUP=coverage
  global:
    - secure: U72nmzXq7kXcIabiwvrTF+WkNFQxov2ACd8oPxWSHsyzRsfVJN42vT7gS3dLbH5G5claXG2p+rur4ueVffzYSwJ8B9OP6gTB8sNJnGr9zyxni4OJchyKqOYuj+UBpEQC/7qXKMCKnuJndsf1OvndDh/V1SH0DSSUuA6mDtgO/eM=
    - secure: WiK7tyFV68xdkIfUlWreUHgEGGjaCBd73O4SbjE9AsbqqF7D+Iu8iRo1OhKQj+6eajUH9Eoev9rVN74FQgUfeNzrOkYsgDysXmyZ7+UxFokijFcATJmIBompA3dySGU2qXeKbJMNuUjXgrRIludaV6h2ahL6Fji42cgK4I3s2qs=

jdk:
  - openjdk8
