language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
  - java -Xmx32m -version

script:
  - ./gradlew --no-daemon clean assemble
  - ./gradlew --no-daemon check 
  - ./gradlew --no-daemon clean check -PuseHadoop2

jdk:
  - oraclejdk8
  - oraclejdk7
