/*module.exports = {
  Docs: {
    Docusaurus: ['index'],
    Features: ['mdx'],
    Docs: ['Getting-Started'],
  },
};
*/

module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'doc',
      id: 'Getting-Started',
    },
    {
      type: 'doc',
      id: 'Gobblin-Architecture',
    },
    {
      type: 'category',
      label: 'User Guide', // generate sidebar slice from docs/api (or versioned_docs/version/api)
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide', // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ]
    },
    {
      type: 'category',
      label: 'Sources', // generate sidebar slice from docs/api (or versioned_docs/version/api)
      items: [
        {
          type: 'autogenerated',
          dirName: 'sources', // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ]
    },
    {
      type: 'category',
      label: 'Gobblin Adaptors',
      items: [
        'adaptors/Gobblin-Distcp',
        'adaptors/Hive-Avro-To-ORC-Converter',
      ],
    },
    {
      type: 'category',
      label: 'Case Studies',
      items: [
        'case-studies/Kafka-HDFS-Ingestion',
        'case-studies/Publishing-Data-to-S3',
        'case-studies/Writing-ORC-Data',
        'case-studies/Hive-Distcp',
      ],
    },
    {
      type: 'category',
      label: 'Gobblin Data Management',
      items: [
        'data-management/Gobblin-Retention',
        'data-management/DistcpNgEvents',
      ],
    },
    {
      type: 'category',
      label: 'Gobblin Metrics',
      items: [
        'metrics/Gobblin-Metrics',
        'metrics/Existing-Reporters',
        'metrics/Metrics-for-Gobblin-ETL',
        'metrics/Gobblin-Metrics-Architecture',
        'metrics/Implementing-New-Reporters',
        'metrics/Gobblin-Metrics-Performance',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/Customization-for-New-Source',
        'developer-guide/Customization-for-Converter-and-Operator',
        'developer-guide/CodingStyle',
        'developer-guide/Gobblin-Compliance-Design',
        'developer-guide/IDE-setup',
        'developer-guide/Monitoring-Design',
        'developer-guide/Documentation-Architecture',
        'developer-guide/Contributing',
        'developer-guide/GobblinModules',
        'developer-guide/HighLevelConsumer',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      items: [
        'project/Feature-List',
        'project/Talks-and-Tech-Blogs',
        'project/Posts',
      ],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: [
        'miscellaneous/Camus-to-Gobblin-Migration',
        'miscellaneous/Exactly-Once-Support',
      ],
    },

  ]
};
