.PHONY: apply
apply:
	kubectl apply -f vol.yml
	kubectl apply -f vol-clm.yml


.PHONY: dummy
dummy:
	kubectl apply -f dummy.yml

.PHONY: pod
pod:
	kubectl apply -f pod.yml


.PHONY: events
events:
	kubectl get events

