apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/a"
