// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogFile.proto

package gobblin.converter.s3;

public final class LogFileOuterClass {
  private LogFileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>required double time_taken = 3;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    boolean hasTimeTaken();
    /**
     * <code>required double time_taken = 3;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    double getTimeTaken();

    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    boolean hasSHost();
    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    java.lang.String getSHost();
    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    com.google.protobuf.ByteString
        getSHostBytes();

    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    boolean hasUri();
    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    java.lang.String getUri();
    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>required int32 sc_status = 6;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    boolean hasScStatus();
    /**
     * <code>required int32 sc_status = 6;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    int getScStatus();

    /**
     * <code>required int32 sc_bytes = 7;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    boolean hasScBytes();
    /**
     * <code>required int32 sc_bytes = 7;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    int getScBytes();

    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    boolean hasCsMethod();
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    java.lang.String getCsMethod();
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    com.google.protobuf.ByteString
        getCsMethodBytes();

    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    boolean hasCIp();
    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    java.lang.String getCIp();
    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getCIpBytes();

    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    boolean hasCPort();
    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    java.lang.String getCPort();
    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    com.google.protobuf.ByteString
        getCPortBytes();

    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    boolean hasReferrer();
    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    java.lang.String getReferrer();
    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    com.google.protobuf.ByteString
        getReferrerBytes();

    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();
  }
  /**
   * Protobuf type {@code LogFile}
   *
   * <pre>
   * Represents a log file. 
   * Draws inspiration from the following formats:
   *    - W3 Extended Logfile: http://www.w3.org/TR/WD-logfile.html
   *    - Amazon Elastic Load Balancing Log Entires: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#access-log-entry-format
   *    - Amazon CloudFront Log File Format: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#LogFileFormat
   * </pre>
   */
  public static final class LogFile extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LogFile)
      LogFileOrBuilder {
    // Use LogFile.newBuilder() to construct.
    private LogFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogFile defaultInstance;
    public static LogFile getDefaultInstance() {
      return defaultInstance;
    }

    public LogFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              date_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              time_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              timeTaken_ = input.readDouble();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sHost_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              uri_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              scStatus_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              scBytes_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              name_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              csMethod_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              cIp_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              cPort_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              referrer_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              userAgent_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gobblin.converter.s3.LogFileOuterClass.internal_static_LogFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gobblin.converter.s3.LogFileOuterClass.internal_static_LogFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gobblin.converter.s3.LogFileOuterClass.LogFile.class, gobblin.converter.s3.LogFileOuterClass.LogFile.Builder.class);
    }

    public static com.google.protobuf.Parser<LogFile> PARSER =
        new com.google.protobuf.AbstractParser<LogFile>() {
      public LogFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogFile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogFile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_TAKEN_FIELD_NUMBER = 3;
    private double timeTaken_;
    /**
     * <code>required double time_taken = 3;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    public boolean hasTimeTaken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double time_taken = 3;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    public double getTimeTaken() {
      return timeTaken_;
    }

    public static final int S_HOST_FIELD_NUMBER = 4;
    private java.lang.Object sHost_;
    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public boolean hasSHost() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public java.lang.String getSHost() {
      java.lang.Object ref = sHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s_host = 4;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSHostBytes() {
      java.lang.Object ref = sHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 5;
    private java.lang.Object uri_;
    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uri = 5;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SC_STATUS_FIELD_NUMBER = 6;
    private int scStatus_;
    /**
     * <code>required int32 sc_status = 6;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    public boolean hasScStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 sc_status = 6;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    public int getScStatus() {
      return scStatus_;
    }

    public static final int SC_BYTES_FIELD_NUMBER = 7;
    private int scBytes_;
    /**
     * <code>required int32 sc_bytes = 7;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    public boolean hasScBytes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 sc_bytes = 7;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    public int getScBytes() {
      return scBytes_;
    }

    public static final int NAME_FIELD_NUMBER = 8;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CS_METHOD_FIELD_NUMBER = 9;
    private java.lang.Object csMethod_;
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public boolean hasCsMethod() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public java.lang.String getCsMethod() {
      java.lang.Object ref = csMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          csMethod_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCsMethodBytes() {
      java.lang.Object ref = csMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        csMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_IP_FIELD_NUMBER = 10;
    private java.lang.Object cIp_;
    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public boolean hasCIp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public java.lang.String getCIp() {
      java.lang.Object ref = cIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c_ip = 10;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCIpBytes() {
      java.lang.Object ref = cIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_PORT_FIELD_NUMBER = 11;
    private java.lang.Object cPort_;
    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public boolean hasCPort() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public java.lang.String getCPort() {
      java.lang.Object ref = cPort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c_port = 11;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCPortBytes() {
      java.lang.Object ref = cPort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERRER_FIELD_NUMBER = 12;
    private java.lang.Object referrer_;
    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public boolean hasReferrer() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public java.lang.String getReferrer() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referrer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string referrer = 12;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReferrerBytes() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referrer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_AGENT_FIELD_NUMBER = 13;
    private java.lang.Object userAgent_;
    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_agent = 13;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      date_ = "";
      time_ = "";
      timeTaken_ = 0D;
      sHost_ = "";
      uri_ = "";
      scStatus_ = 0;
      scBytes_ = 0;
      name_ = "";
      csMethod_ = "";
      cIp_ = "";
      cPort_ = "";
      referrer_ = "";
      userAgent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeTaken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, timeTaken_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSHostBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUriBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, scStatus_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, scBytes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCsMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getCIpBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getCPortBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getReferrerBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getUserAgentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, timeTaken_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSHostBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUriBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, scStatus_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, scBytes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCsMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCIpBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getCPortBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getReferrerBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getUserAgentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gobblin.converter.s3.LogFileOuterClass.LogFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gobblin.converter.s3.LogFileOuterClass.LogFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogFile}
     *
     * <pre>
     * Represents a log file. 
     * Draws inspiration from the following formats:
     *    - W3 Extended Logfile: http://www.w3.org/TR/WD-logfile.html
     *    - Amazon Elastic Load Balancing Log Entires: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#access-log-entry-format
     *    - Amazon CloudFront Log File Format: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#LogFileFormat
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogFile)
        gobblin.converter.s3.LogFileOuterClass.LogFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gobblin.converter.s3.LogFileOuterClass.internal_static_LogFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gobblin.converter.s3.LogFileOuterClass.internal_static_LogFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gobblin.converter.s3.LogFileOuterClass.LogFile.class, gobblin.converter.s3.LogFileOuterClass.LogFile.Builder.class);
      }

      // Construct using gobblin.converter.s3.LogFileOuterClass.LogFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timeTaken_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        sHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        scStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        scBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        csMethod_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        cIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        cPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        referrer_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gobblin.converter.s3.LogFileOuterClass.internal_static_LogFile_descriptor;
      }

      public gobblin.converter.s3.LogFileOuterClass.LogFile getDefaultInstanceForType() {
        return gobblin.converter.s3.LogFileOuterClass.LogFile.getDefaultInstance();
      }

      public gobblin.converter.s3.LogFileOuterClass.LogFile build() {
        gobblin.converter.s3.LogFileOuterClass.LogFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gobblin.converter.s3.LogFileOuterClass.LogFile buildPartial() {
        gobblin.converter.s3.LogFileOuterClass.LogFile result = new gobblin.converter.s3.LogFileOuterClass.LogFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeTaken_ = timeTaken_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sHost_ = sHost_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.scStatus_ = scStatus_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.scBytes_ = scBytes_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.csMethod_ = csMethod_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cIp_ = cIp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.cPort_ = cPort_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.referrer_ = referrer_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.userAgent_ = userAgent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gobblin.converter.s3.LogFileOuterClass.LogFile) {
          return mergeFrom((gobblin.converter.s3.LogFileOuterClass.LogFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gobblin.converter.s3.LogFileOuterClass.LogFile other) {
        if (other == gobblin.converter.s3.LogFileOuterClass.LogFile.getDefaultInstance()) return this;
        if (other.hasDate()) {
          bitField0_ |= 0x00000001;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasTimeTaken()) {
          setTimeTaken(other.getTimeTaken());
        }
        if (other.hasSHost()) {
          bitField0_ |= 0x00000008;
          sHost_ = other.sHost_;
          onChanged();
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000010;
          uri_ = other.uri_;
          onChanged();
        }
        if (other.hasScStatus()) {
          setScStatus(other.getScStatus());
        }
        if (other.hasScBytes()) {
          setScBytes(other.getScBytes());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000080;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCsMethod()) {
          bitField0_ |= 0x00000100;
          csMethod_ = other.csMethod_;
          onChanged();
        }
        if (other.hasCIp()) {
          bitField0_ |= 0x00000200;
          cIp_ = other.cIp_;
          onChanged();
        }
        if (other.hasCPort()) {
          bitField0_ |= 0x00000400;
          cPort_ = other.cPort_;
          onChanged();
        }
        if (other.hasReferrer()) {
          bitField0_ |= 0x00000800;
          referrer_ = other.referrer_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00001000;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasTimeTaken()) {
          
          return false;
        }
        if (!hasSHost()) {
          
          return false;
        }
        if (!hasUri()) {
          
          return false;
        }
        if (!hasScStatus()) {
          
          return false;
        }
        if (!hasScBytes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gobblin.converter.s3.LogFileOuterClass.LogFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gobblin.converter.s3.LogFileOuterClass.LogFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      private double timeTaken_ ;
      /**
       * <code>required double time_taken = 3;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public boolean hasTimeTaken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double time_taken = 3;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public double getTimeTaken() {
        return timeTaken_;
      }
      /**
       * <code>required double time_taken = 3;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public Builder setTimeTaken(double value) {
        bitField0_ |= 0x00000004;
        timeTaken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time_taken = 3;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public Builder clearTimeTaken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeTaken_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object sHost_ = "";
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public boolean hasSHost() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public java.lang.String getSHost() {
        java.lang.Object ref = sHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSHostBytes() {
        java.lang.Object ref = sHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder setSHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder clearSHost() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sHost_ = getDefaultInstance().getSHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string s_host = 4;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder setSHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sHost_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 5;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uri_ = value;
        onChanged();
        return this;
      }

      private int scStatus_ ;
      /**
       * <code>required int32 sc_status = 6;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public boolean hasScStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 sc_status = 6;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public int getScStatus() {
        return scStatus_;
      }
      /**
       * <code>required int32 sc_status = 6;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public Builder setScStatus(int value) {
        bitField0_ |= 0x00000020;
        scStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sc_status = 6;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public Builder clearScStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        scStatus_ = 0;
        onChanged();
        return this;
      }

      private int scBytes_ ;
      /**
       * <code>required int32 sc_bytes = 7;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public boolean hasScBytes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 sc_bytes = 7;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public int getScBytes() {
        return scBytes_;
      }
      /**
       * <code>required int32 sc_bytes = 7;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public Builder setScBytes(int value) {
        bitField0_ |= 0x00000040;
        scBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sc_bytes = 7;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public Builder clearScBytes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scBytes_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object csMethod_ = "";
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public boolean hasCsMethod() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public java.lang.String getCsMethod() {
        java.lang.Object ref = csMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            csMethod_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCsMethodBytes() {
        java.lang.Object ref = csMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          csMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder setCsMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        csMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder clearCsMethod() {
        bitField0_ = (bitField0_ & ~0x00000100);
        csMethod_ = getDefaultInstance().getCsMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder setCsMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        csMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cIp_ = "";
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public boolean hasCIp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public java.lang.String getCIp() {
        java.lang.Object ref = cIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCIpBytes() {
        java.lang.Object ref = cIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder setCIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder clearCIp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cIp_ = getDefaultInstance().getCIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_ip = 10;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder setCIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cPort_ = "";
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public boolean hasCPort() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public java.lang.String getCPort() {
        java.lang.Object ref = cPort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cPort_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCPortBytes() {
        java.lang.Object ref = cPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder setCPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        cPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder clearCPort() {
        bitField0_ = (bitField0_ & ~0x00000400);
        cPort_ = getDefaultInstance().getCPort();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_port = 11;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder setCPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        cPort_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object referrer_ = "";
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public boolean hasReferrer() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public java.lang.String getReferrer() {
        java.lang.Object ref = referrer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            referrer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReferrerBytes() {
        java.lang.Object ref = referrer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referrer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder setReferrer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        referrer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder clearReferrer() {
        bitField0_ = (bitField0_ & ~0x00000800);
        referrer_ = getDefaultInstance().getReferrer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 12;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder setReferrerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        referrer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userAgent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00001000);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 13;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LogFile)
    }

    static {
      defaultInstance = new LogFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LogFile)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rLogFile.proto\"\340\001\n\007LogFile\022\014\n\004date\030\001 \002(" +
      "\t\022\014\n\004time\030\002 \002(\t\022\022\n\ntime_taken\030\003 \002(\001\022\016\n\006s" +
      "_host\030\004 \002(\t\022\013\n\003uri\030\005 \002(\t\022\021\n\tsc_status\030\006 " +
      "\002(\005\022\020\n\010sc_bytes\030\007 \002(\005\022\014\n\004name\030\010 \001(\t\022\021\n\tc" +
      "s_method\030\t \001(\t\022\014\n\004c_ip\030\n \001(\t\022\016\n\006c_port\030\013" +
      " \001(\t\022\020\n\010referrer\030\014 \001(\t\022\022\n\nuser_agent\030\r \001" +
      "(\tB\026\n\024gobblin.converter.s3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LogFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogFile_descriptor,
        new java.lang.String[] { "Date", "Time", "TimeTaken", "SHost", "Uri", "ScStatus", "ScBytes", "Name", "CsMethod", "CIp", "CPort", "Referrer", "UserAgent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
