// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogFile.proto

package gobblin.converter.s3;

public final class LogFileProtobuf {
  private LogFileProtobuf() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code logfile.Environment}
   *
   * <pre>
   * The environment the log file was generated in
   * </pre>
   */
  public enum Environment
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEV = 1;</code>
     */
    DEV(0, 1),
    /**
     * <code>PROD = 2;</code>
     */
    PROD(1, 2),
    /**
     * <code>STAGE = 3;</code>
     */
    STAGE(2, 3),
    ;

    /**
     * <code>DEV = 1;</code>
     */
    public static final int DEV_VALUE = 1;
    /**
     * <code>PROD = 2;</code>
     */
    public static final int PROD_VALUE = 2;
    /**
     * <code>STAGE = 3;</code>
     */
    public static final int STAGE_VALUE = 3;


    public final int getNumber() { return value; }

    public static Environment valueOf(int value) {
      switch (value) {
        case 1: return DEV;
        case 2: return PROD;
        case 3: return STAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Environment>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Environment>
            internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Environment>() {
              public Environment findValueByNumber(int number) {
                return Environment.valueOf(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return gobblin.converter.s3.LogFileProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final Environment[] VALUES = values();

    public static Environment valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Environment(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:logfile.Environment)
  }

  public interface LogFileOrBuilder extends
          // @@protoc_insertion_point(interface_extends:logfile.LogFile)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .logfile.Environment environment = 1;</code>
     */
    boolean hasEnvironment();
    /**
     * <code>required .logfile.Environment environment = 1;</code>
     */
    gobblin.converter.s3.LogFileProtobuf.Environment getEnvironment();

    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    com.google.protobuf.ByteString
    getDateBytes();

    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    com.google.protobuf.ByteString
    getTimeBytes();

    /**
     * <code>required double time_taken = 4;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    boolean hasTimeTaken();
    /**
     * <code>required double time_taken = 4;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    double getTimeTaken();

    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    boolean hasSHost();
    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    java.lang.String getSHost();
    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    com.google.protobuf.ByteString
    getSHostBytes();

    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    boolean hasCIp();
    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    java.lang.String getCIp();
    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    com.google.protobuf.ByteString
    getCIpBytes();

    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    boolean hasCPort();
    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    java.lang.String getCPort();
    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    com.google.protobuf.ByteString
    getCPortBytes();

    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    boolean hasCsMethod();
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    java.lang.String getCsMethod();
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    com.google.protobuf.ByteString
    getCsMethodBytes();

    /**
     * <code>required int32 sc_status = 10;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    boolean hasScStatus();
    /**
     * <code>required int32 sc_status = 10;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    int getScStatus();

    /**
     * <code>required int32 sc_bytes = 11;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    boolean hasScBytes();
    /**
     * <code>required int32 sc_bytes = 11;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    int getScBytes();

    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    boolean hasUri();
    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    java.lang.String getUri();
    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    com.google.protobuf.ByteString
    getUriBytes();

    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    boolean hasReferrer();
    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    java.lang.String getReferrer();
    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    com.google.protobuf.ByteString
    getReferrerBytes();

    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    com.google.protobuf.ByteString
    getUserAgentBytes();
  }
  /**
   * Protobuf type {@code logfile.LogFile}
   *
   * <pre>
   * Represents a log file. 
   * Draws inspiration from the following formats:
   *    - W3 Extended Logfile: http://www.w3.org/TR/WD-logfile.html
   *    - Amazon Elastic Load Balancing Log Entires: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#access-log-entry-format
   *    - Amazon CloudFront Log File Format: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#LogFileFormat
   * </pre>
   */
  public static final class LogFile extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:logfile.LogFile)
          LogFileOrBuilder {
    // Use LogFile.newBuilder() to construct.
    private LogFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogFile defaultInstance;
    public static LogFile getDefaultInstance() {
      return defaultInstance;
    }

    public LogFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogFile(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gobblin.converter.s3.LogFileProtobuf.Environment value = gobblin.converter.s3.LogFileProtobuf.Environment.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                environment_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              date_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              time_ = bs;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              timeTaken_ = input.readDouble();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              name_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              sHost_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              cIp_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              cPort_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              csMethod_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              scStatus_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              scBytes_ = input.readInt32();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              uri_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              referrer_ = bs;
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              userAgent_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return gobblin.converter.s3.LogFileProtobuf.internal_static_logfile_LogFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return gobblin.converter.s3.LogFileProtobuf.internal_static_logfile_LogFile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      gobblin.converter.s3.LogFileProtobuf.LogFile.class, gobblin.converter.s3.LogFileProtobuf.LogFile.Builder.class);
    }

    public static com.google.protobuf.Parser<LogFile> PARSER =
            new com.google.protobuf.AbstractParser<LogFile>() {
              public LogFile parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new LogFile(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<LogFile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENVIRONMENT_FIELD_NUMBER = 1;
    private gobblin.converter.s3.LogFileProtobuf.Environment environment_;
    /**
     * <code>required .logfile.Environment environment = 1;</code>
     */
    public boolean hasEnvironment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .logfile.Environment environment = 1;</code>
     */
    public gobblin.converter.s3.LogFileProtobuf.Environment getEnvironment() {
      return environment_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Date of the request (YYYY-MM-DD)
     * </pre>
     */
    public com.google.protobuf.ByteString
    getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private java.lang.Object time_;
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Time the server finished processing the request (HH:MM:SS)
     * </pre>
     */
    public com.google.protobuf.ByteString
    getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_TAKEN_FIELD_NUMBER = 4;
    private double timeTaken_;
    /**
     * <code>required double time_taken = 4;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    public boolean hasTimeTaken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double time_taken = 4;</code>
     *
     * <pre>
     * Time taken to process request (from server receive to last byte sent)
     * </pre>
     */
    public double getTimeTaken() {
      return timeTaken_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * Name  (x-edge-location for CloudFront, elb name, etc)
     * </pre>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_HOST_FIELD_NUMBER = 6;
    private java.lang.Object sHost_;
    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public boolean hasSHost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public java.lang.String getSHost() {
      java.lang.Object ref = sHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s_host = 6;</code>
     *
     * <pre>
     * IP/DNS name of the host
     * </pre>
     */
    public com.google.protobuf.ByteString
    getSHostBytes() {
      java.lang.Object ref = sHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        sHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_IP_FIELD_NUMBER = 7;
    private java.lang.Object cIp_;
    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public boolean hasCIp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public java.lang.String getCIp() {
      java.lang.Object ref = cIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c_ip = 7;</code>
     *
     * <pre>
     * Client IP
     * </pre>
     */
    public com.google.protobuf.ByteString
    getCIpBytes() {
      java.lang.Object ref = cIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        cIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_PORT_FIELD_NUMBER = 8;
    private java.lang.Object cPort_;
    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public boolean hasCPort() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public java.lang.String getCPort() {
      java.lang.Object ref = cPort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c_port = 8;</code>
     *
     * <pre>
     * Client Port
     * </pre>
     */
    public com.google.protobuf.ByteString
    getCPortBytes() {
      java.lang.Object ref = cPort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        cPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CS_METHOD_FIELD_NUMBER = 9;
    private java.lang.Object csMethod_;
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public boolean hasCsMethod() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public java.lang.String getCsMethod() {
      java.lang.Object ref = csMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          csMethod_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cs_method = 9;</code>
     *
     * <pre>
     * The request method (GET, POST, etc)
     * </pre>
     */
    public com.google.protobuf.ByteString
    getCsMethodBytes() {
      java.lang.Object ref = csMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        csMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SC_STATUS_FIELD_NUMBER = 10;
    private int scStatus_;
    /**
     * <code>required int32 sc_status = 10;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    public boolean hasScStatus() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 sc_status = 10;</code>
     *
     * <pre>
     * Response status code (2xx, 4xx, etc)
     * </pre>
     */
    public int getScStatus() {
      return scStatus_;
    }

    public static final int SC_BYTES_FIELD_NUMBER = 11;
    private int scBytes_;
    /**
     * <code>required int32 sc_bytes = 11;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    public boolean hasScBytes() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 sc_bytes = 11;</code>
     *
     * <pre>
     * Server to client bytes sent
     * </pre>
     */
    public int getScBytes() {
      return scBytes_;
    }

    public static final int URI_FIELD_NUMBER = 12;
    private java.lang.Object uri_;
    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uri = 12;</code>
     *
     * <pre>
     * Full URI of the request (query + stem)
     * </pre>
     */
    public com.google.protobuf.ByteString
    getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERRER_FIELD_NUMBER = 13;
    private java.lang.Object referrer_;
    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public boolean hasReferrer() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public java.lang.String getReferrer() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referrer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string referrer = 13;</code>
     *
     * <pre>
     * The referrer, if any
     * </pre>
     */
    public com.google.protobuf.ByteString
    getReferrerBytes() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        referrer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_AGENT_FIELD_NUMBER = 14;
    private java.lang.Object userAgent_;
    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_agent = 14;</code>
     *
     * <pre>
     * User agent string
     * </pre>
     */
    public com.google.protobuf.ByteString
    getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      environment_ = gobblin.converter.s3.LogFileProtobuf.Environment.DEV;
      date_ = "";
      time_ = "";
      timeTaken_ = 0D;
      name_ = "";
      sHost_ = "";
      cIp_ = "";
      cPort_ = "";
      csMethod_ = "";
      scStatus_ = 0;
      scBytes_ = 0;
      uri_ = "";
      referrer_ = "";
      userAgent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEnvironment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeTaken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, environment_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, timeTaken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCIpBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getCPortBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCsMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, scStatus_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, scBytes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getUriBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getReferrerBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getUserAgentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(1, environment_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeDoubleSize(4, timeTaken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(6, getSHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(7, getCIpBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(8, getCPortBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(9, getCsMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(10, scStatus_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(11, scBytes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(12, getUriBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(13, getReferrerBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(14, getUserAgentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gobblin.converter.s3.LogFileProtobuf.LogFile parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gobblin.converter.s3.LogFileProtobuf.LogFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code logfile.LogFile}
     *
     * <pre>
     * Represents a log file. 
     * Draws inspiration from the following formats:
     *    - W3 Extended Logfile: http://www.w3.org/TR/WD-logfile.html
     *    - Amazon Elastic Load Balancing Log Entires: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#access-log-entry-format
     *    - Amazon CloudFront Log File Format: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#LogFileFormat
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:logfile.LogFile)
            gobblin.converter.s3.LogFileProtobuf.LogFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return gobblin.converter.s3.LogFileProtobuf.internal_static_logfile_LogFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return gobblin.converter.s3.LogFileProtobuf.internal_static_logfile_LogFile_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        gobblin.converter.s3.LogFileProtobuf.LogFile.class, gobblin.converter.s3.LogFileProtobuf.LogFile.Builder.class);
      }

      // Construct using gobblin.converter.s3.LogFileProtobuf.LogFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        environment_ = gobblin.converter.s3.LogFileProtobuf.Environment.DEV;
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timeTaken_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        cPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        csMethod_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        scStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        scBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        referrer_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return gobblin.converter.s3.LogFileProtobuf.internal_static_logfile_LogFile_descriptor;
      }

      public gobblin.converter.s3.LogFileProtobuf.LogFile getDefaultInstanceForType() {
        return gobblin.converter.s3.LogFileProtobuf.LogFile.getDefaultInstance();
      }

      public gobblin.converter.s3.LogFileProtobuf.LogFile build() {
        gobblin.converter.s3.LogFileProtobuf.LogFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gobblin.converter.s3.LogFileProtobuf.LogFile buildPartial() {
        gobblin.converter.s3.LogFileProtobuf.LogFile result = new gobblin.converter.s3.LogFileProtobuf.LogFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.environment_ = environment_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeTaken_ = timeTaken_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sHost_ = sHost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cIp_ = cIp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cPort_ = cPort_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.csMethod_ = csMethod_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.scStatus_ = scStatus_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.scBytes_ = scBytes_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.referrer_ = referrer_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.userAgent_ = userAgent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gobblin.converter.s3.LogFileProtobuf.LogFile) {
          return mergeFrom((gobblin.converter.s3.LogFileProtobuf.LogFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gobblin.converter.s3.LogFileProtobuf.LogFile other) {
        if (other == gobblin.converter.s3.LogFileProtobuf.LogFile.getDefaultInstance()) return this;
        if (other.hasEnvironment()) {
          setEnvironment(other.getEnvironment());
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000004;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasTimeTaken()) {
          setTimeTaken(other.getTimeTaken());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSHost()) {
          bitField0_ |= 0x00000020;
          sHost_ = other.sHost_;
          onChanged();
        }
        if (other.hasCIp()) {
          bitField0_ |= 0x00000040;
          cIp_ = other.cIp_;
          onChanged();
        }
        if (other.hasCPort()) {
          bitField0_ |= 0x00000080;
          cPort_ = other.cPort_;
          onChanged();
        }
        if (other.hasCsMethod()) {
          bitField0_ |= 0x00000100;
          csMethod_ = other.csMethod_;
          onChanged();
        }
        if (other.hasScStatus()) {
          setScStatus(other.getScStatus());
        }
        if (other.hasScBytes()) {
          setScBytes(other.getScBytes());
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000800;
          uri_ = other.uri_;
          onChanged();
        }
        if (other.hasReferrer()) {
          bitField0_ |= 0x00001000;
          referrer_ = other.referrer_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00002000;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEnvironment()) {

          return false;
        }
        if (!hasDate()) {

          return false;
        }
        if (!hasTime()) {

          return false;
        }
        if (!hasTimeTaken()) {

          return false;
        }
        if (!hasSHost()) {

          return false;
        }
        if (!hasScStatus()) {

          return false;
        }
        if (!hasScBytes()) {

          return false;
        }
        if (!hasUri()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        gobblin.converter.s3.LogFileProtobuf.LogFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gobblin.converter.s3.LogFileProtobuf.LogFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private gobblin.converter.s3.LogFileProtobuf.Environment environment_ = gobblin.converter.s3.LogFileProtobuf.Environment.DEV;
      /**
       * <code>required .logfile.Environment environment = 1;</code>
       */
      public boolean hasEnvironment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .logfile.Environment environment = 1;</code>
       */
      public gobblin.converter.s3.LogFileProtobuf.Environment getEnvironment() {
        return environment_;
      }
      /**
       * <code>required .logfile.Environment environment = 1;</code>
       */
      public Builder setEnvironment(gobblin.converter.s3.LogFileProtobuf.Environment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        environment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .logfile.Environment environment = 1;</code>
       */
      public Builder clearEnvironment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        environment_ = gobblin.converter.s3.LogFileProtobuf.Environment.DEV;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public com.google.protobuf.ByteString
      getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder setDate(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Date of the request (YYYY-MM-DD)
       * </pre>
       */
      public Builder setDateBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public com.google.protobuf.ByteString
      getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder setTime(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Time the server finished processing the request (HH:MM:SS)
       * </pre>
       */
      public Builder setTimeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }

      private double timeTaken_ ;
      /**
       * <code>required double time_taken = 4;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public boolean hasTimeTaken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double time_taken = 4;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public double getTimeTaken() {
        return timeTaken_;
      }
      /**
       * <code>required double time_taken = 4;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public Builder setTimeTaken(double value) {
        bitField0_ |= 0x00000008;
        timeTaken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time_taken = 4;</code>
       *
       * <pre>
       * Time taken to process request (from server receive to last byte sent)
       * </pre>
       */
      public Builder clearTimeTaken() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeTaken_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder setName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * Name  (x-edge-location for CloudFront, elb name, etc)
       * </pre>
       */
      public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sHost_ = "";
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public boolean hasSHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public java.lang.String getSHost() {
        java.lang.Object ref = sHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public com.google.protobuf.ByteString
      getSHostBytes() {
        java.lang.Object ref = sHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          sHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder setSHost(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        sHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder clearSHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sHost_ = getDefaultInstance().getSHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string s_host = 6;</code>
       *
       * <pre>
       * IP/DNS name of the host
       * </pre>
       */
      public Builder setSHostBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        sHost_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cIp_ = "";
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public boolean hasCIp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public java.lang.String getCIp() {
        java.lang.Object ref = cIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public com.google.protobuf.ByteString
      getCIpBytes() {
        java.lang.Object ref = cIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          cIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder setCIp(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        cIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder clearCIp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cIp_ = getDefaultInstance().getCIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_ip = 7;</code>
       *
       * <pre>
       * Client IP
       * </pre>
       */
      public Builder setCIpBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        cIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cPort_ = "";
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public boolean hasCPort() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public java.lang.String getCPort() {
        java.lang.Object ref = cPort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cPort_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public com.google.protobuf.ByteString
      getCPortBytes() {
        java.lang.Object ref = cPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          cPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder setCPort(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        cPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder clearCPort() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cPort_ = getDefaultInstance().getCPort();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c_port = 8;</code>
       *
       * <pre>
       * Client Port
       * </pre>
       */
      public Builder setCPortBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        cPort_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object csMethod_ = "";
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public boolean hasCsMethod() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public java.lang.String getCsMethod() {
        java.lang.Object ref = csMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            csMethod_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public com.google.protobuf.ByteString
      getCsMethodBytes() {
        java.lang.Object ref = csMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          csMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder setCsMethod(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        csMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder clearCsMethod() {
        bitField0_ = (bitField0_ & ~0x00000100);
        csMethod_ = getDefaultInstance().getCsMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cs_method = 9;</code>
       *
       * <pre>
       * The request method (GET, POST, etc)
       * </pre>
       */
      public Builder setCsMethodBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        csMethod_ = value;
        onChanged();
        return this;
      }

      private int scStatus_ ;
      /**
       * <code>required int32 sc_status = 10;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public boolean hasScStatus() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 sc_status = 10;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public int getScStatus() {
        return scStatus_;
      }
      /**
       * <code>required int32 sc_status = 10;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public Builder setScStatus(int value) {
        bitField0_ |= 0x00000200;
        scStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sc_status = 10;</code>
       *
       * <pre>
       * Response status code (2xx, 4xx, etc)
       * </pre>
       */
      public Builder clearScStatus() {
        bitField0_ = (bitField0_ & ~0x00000200);
        scStatus_ = 0;
        onChanged();
        return this;
      }

      private int scBytes_ ;
      /**
       * <code>required int32 sc_bytes = 11;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public boolean hasScBytes() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 sc_bytes = 11;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public int getScBytes() {
        return scBytes_;
      }
      /**
       * <code>required int32 sc_bytes = 11;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public Builder setScBytes(int value) {
        bitField0_ |= 0x00000400;
        scBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sc_bytes = 11;</code>
       *
       * <pre>
       * Server to client bytes sent
       * </pre>
       */
      public Builder clearScBytes() {
        bitField0_ = (bitField0_ & ~0x00000400);
        scBytes_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public com.google.protobuf.ByteString
      getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder setUri(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000800;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000800);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 12;</code>
       *
       * <pre>
       * Full URI of the request (query + stem)
       * </pre>
       */
      public Builder setUriBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000800;
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object referrer_ = "";
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public boolean hasReferrer() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public java.lang.String getReferrer() {
        java.lang.Object ref = referrer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            referrer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public com.google.protobuf.ByteString
      getReferrerBytes() {
        java.lang.Object ref = referrer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          referrer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder setReferrer(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00001000;
        referrer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder clearReferrer() {
        bitField0_ = (bitField0_ & ~0x00001000);
        referrer_ = getDefaultInstance().getReferrer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 13;</code>
       *
       * <pre>
       * The referrer, if any
       * </pre>
       */
      public Builder setReferrerBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00001000;
        referrer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userAgent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public com.google.protobuf.ByteString
      getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder setUserAgent(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00002000;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00002000);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 14;</code>
       *
       * <pre>
       * User agent string
       * </pre>
       */
      public Builder setUserAgentBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00002000;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:logfile.LogFile)
    }

    static {
      defaultInstance = new LogFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:logfile.LogFile)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_logfile_LogFile_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_logfile_LogFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rLogFile.proto\022\007logfile\"\213\002\n\007LogFile\022)\n\013" +
                    "environment\030\001 \002(\0162\024.logfile.Environment\022" +
                    "\014\n\004date\030\002 \002(\t\022\014\n\004time\030\003 \002(\t\022\022\n\ntime_take" +
                    "n\030\004 \002(\001\022\014\n\004name\030\005 \001(\t\022\016\n\006s_host\030\006 \002(\t\022\014\n" +
                    "\004c_ip\030\007 \001(\t\022\016\n\006c_port\030\010 \001(\t\022\021\n\tcs_method" +
                    "\030\t \001(\t\022\021\n\tsc_status\030\n \002(\005\022\020\n\010sc_bytes\030\013 " +
                    "\002(\005\022\013\n\003uri\030\014 \002(\t\022\020\n\010referrer\030\r \001(\t\022\022\n\nus" +
                    "er_agent\030\016 \001(\t*+\n\013Environment\022\007\n\003DEV\020\001\022\010" +
                    "\n\004PROD\020\002\022\t\n\005STAGE\020\003B\'\n\024gobblin.converter" +
                    ".s3B\017LogFileProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_logfile_LogFile_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_logfile_LogFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_logfile_LogFile_descriptor,
            new java.lang.String[] { "Environment", "Date", "Time", "TimeTaken", "Name", "SHost", "CIp", "CPort", "CsMethod", "ScStatus", "ScBytes", "Uri", "Referrer", "UserAgent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
