apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gaas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gaas-svc
                port:
                  number: 6956
