apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-jobs-volume
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/etc/opt/job-conf"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-jobs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
