hive.dataset.whitelist=hiveTestDb.testTable

gobblin.retention.dataset.finder.class=gobblin.data.management.retention.dataset.finder.CleanableHiveDatasetFinder

gobblin.retention.selection.policy.class=gobblin.data.management.policy.SelectBeforeTimeBasedPolicy
gobblin.retention.selection.timeBased.lookbackTime=7d
gobblin.retention.version.finder.class=gobblin.data.management.version.finder.DatePartitionHiveVersionFinder

gobblin.retention.hive.partition.key.name=datepartition
gobblin.retention.hive.partition.value.datetime.pattern=yyyy-MM-dd-HH
gobblin.retention.hive.partition.value.datetime.timezone=America/Los_Angeles
gobblin.retention.hive.shouldDeleteData=true